In [33]:
import numpy as np

# Numpy (NumericPython)
Pythonda matematiksel işlemleri hızlı bir biçimde yapabilmemizi sağlayan kütüphane

In [34]:
p_list = list(range(1_000_000)) # Klasik python listesi
np_array = np.array(p_list) # 1m elemanı olan np array

In [35]:
%%timeit
[x+1 for x in p_list]

57.9 ms ± 2.12 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [36]:
%%timeit
np_array + 1

1.93 ms ± 20.8 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [37]:
arr1 = np.array(1)

In [38]:
type(arr1)

numpy.ndarray

In [39]:
arr1.ndim # ndim -> ndimension(boyutu) -> 0

0

In [40]:
arr2 = np.array([10,20,30])
arr2.ndim , arr2.shape # 1D Array (Vector)

(1, (3,))

In [41]:
arr3 = np.array([40,50,60])
arr3.ndim, arr3.shape

(1, (3,))

In [42]:
result = arr2 + arr3
result

array([50, 70, 90])

In [43]:
result2 = arr3 - arr2
result2

array([30, 30, 30])

In [44]:
# Shape uyuşmazlığı olduğu iiçin matematiksel işlemler yapılamaz
arr4 = np.array([100,200])
# arr3 + arr4 

In [49]:
arr5 = np.array(
    [
        [10,20,30],
        [40,50,60]
    ]
)
# 2 boyutlu, 2,3 şekilli bir matris
arr5.ndim, arr5.shape

(2, (2, 3))

In [50]:
arr6 = np.array(
    [
        [70,80,90],
        [100,110,120]
    ]
)
arr6.ndim, arr6.shape

(2, (2, 3))

In [51]:
result = arr5 + arr6
result

array([[ 80, 100, 120],
       [140, 160, 180]])

# Dot Product (İç Çarpım)
Dot product -> ilk matrisin sütun sayısı, ikinci matrisin satır sayısına eşit olmalı

In [52]:
np.dot(arr5,arr6)

ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

In [54]:
arr7 = np.array(
    [
        [10,20,30],
        [40,50,60]
    ]
)

arr8 = np.array([
    [10,20],
    [30,40],
    [50,60]
])
arr7.shape , arr8.shape

((2, 3), (3, 2))

In [57]:
np.dot(arr7, arr8) 

array([[2200, 2800],
       [4900, 6400]])

In [59]:
arr9 = np.array(
    [
        [ [10,20,30,40], [30,40,50,60], [50,60,70,80] ],
        [ [70,80,90,100], [90,100,110,120], [110,120,130,140] ]
    ]
)
# 3D array,
arr9.ndim, arr9.shape

(3, (2, 3, 4))

In [60]:
arr10 = np.random.randint(0,255, (1500,1000))
arr10

array([[246, 115, 189, ..., 209, 115,  64],
       [ 23, 210,  91, ..., 113, 171,  54],
       [222,  72, 101, ...,  55,  33, 190],
       ...,
       [ 58, 213, 226, ..., 196,  27,  36],
       [109,  18, 151, ..., 172, 144,  84],
       [ 67, 151, 106, ..., 147, 188,  90]], dtype=int32)

In [63]:
!pip install Pillow

   ---------------------------------------- 0.0/2.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.6 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.6 MB ? eta -:--:--
   ------- -------------------------------- 0.5/2.6 MB 1.1 MB/s eta 0:00:02
   --------------- ------------------------ 1.0/2.6 MB 1.8 MB/s eta 0:00:01
   ----------------------------------- ---- 2.4/2.6 MB 3.4 MB/s eta 0:00:01
   ---------------------------------------- 2.6/2.6 MB 3.2 MB/s eta 0:00:00


In [64]:
from PIL import Image

In [70]:
image= Image.open("Eminem.png")

In [73]:
image_arr = np.array(image)
image_arr .ndim, image_arr.shape

(3, (618, 620, 4))

In [74]:
image_arr

array([[[255, 255, 255, 255],
        [  0,   0,   0, 255],
        [  0,   0,   0, 255],
        ...,
        [  0,   0,   0, 255],
        [  0,   0,   0, 255],
        [  0,   0,   0, 255]],

       [[255, 255, 255, 255],
        [  0,   0,   0, 255],
        [  0,   0,   0, 255],
        ...,
        [  0,   0,   0, 255],
        [  0,   0,   0, 255],
        [  0,   0,   0, 255]],

       [[255, 255, 255, 255],
        [  0,   0,   0, 255],
        [  0,   0,   0, 255],
        ...,
        [118, 118, 118, 255],
        [ 58,  58,  58, 255],
        [  0,   0,   0, 255]],

       ...,

       [[255, 255, 255, 255],
        [  0,   0,   0, 255],
        [  0,   0,   0, 255],
        ...,
        [178, 226, 246, 255],
        [108, 120, 125, 255],
        [  0,   0,   0, 255]],

       [[255, 255, 255, 255],
        [  0,   0,   0, 255],
        [  0,   0,   0, 255],
        ...,
        [178, 226, 246, 255],
        [108, 120, 125, 255],
        [  0,   0,   0, 255]],

       [[255